name: Release
on:
  push:
    tags:
      - "*/v*.*.*"

jobs:
  tests:
    permissions:
      contents: read
      pull-requests: read
      checks: write
    uses: ./.github/workflows/tests.yml

  release:
    needs: [ tests ]
    name: Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}
          body_path: release.md
      - name: Summary
        run: |
          echo "Release ID: ${{ steps.release.outputs.id }}" >> $GITHUB_STEP_SUMMARY
          echo "Release URL: ${{ steps.release.outputs.url }}" >> $GITHUB_STEP_SUMMARY
