name: Tests
on:
  workflow_call:
  push:
    paths:
      - "**.go"
      - go.mod
      - go.sum
      - .github/workflows/tests.yml

jobs:
  lookup-pkg:
    name: Lookup Packages
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.find-packages.outputs.packages }}
    steps:
      - uses: actions/checkout@v4
      - name: Find Go packages
        id: find-packages
        run: |
          echo "Finding Go packages..."
          packages=$(find . -name "go.mod" -exec dirname {} \; | jq -R . | jq -s . | tr -d '\n')
          echo "Found packages: $packages"
          echo "packages=$packages" >> $GITHUB_OUTPUT

  static_tests:
    name: Static Tests
    needs: [ cache ]
    permissions:
      contents: read
      pull-requests: read
      checks: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ fromJson(needs.lookup-pkg.outputs.packages) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: GolangCI Lint
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: ${{ matrix.package }}
          skip-cache: false


  unit_tests:
    name: Unit Tests
    needs: lookup-pkg
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ fromJson(needs.lookup-pkg.outputs.packages) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Test
        uses: robherley/go-test-action@v0.4.1
        with:
          moduleDirectory: ${{ matrix.package }}
